In [1]:
import pandas as pd
import numpy as np
import seaborn as sb
from sklearn.model_selection import train_test_split
from sklearn.datasets import load_iris
from sklearn.naive_bayes import MultinomialNB
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
import warnings
warnings.filterwarnings('ignore')

In [2]:
df=pd.read_csv('nfl_data.csv')

In [3]:
df

,index,Date(IST),NFO,NFH,NFL,NFC,FIIB,FIIS,FIIN,DIIB,...,August,December,CAD,DAD,DOD,NDAD,Currey,Flow,Shine,Vega
0,1,2020-01-02,12115.673242,12177.119957,12151.571552,12216.272367,2670.78,1982.02,688.76,3490.16,...,1356.0,482.0,-0.01,0.3970,-0.98,0.72,-0.0520,0.0399,-0.10,-1.309999
1,2,2020-01-03,12195.406448,12275.487382,12173.355954,12251.196928,4514.35,3251.30,1263.05,2750.87,...,879.0,973.0,-0.23,-0.5100,-1.33,0.46,0.4430,0.5648,0.08,1.550000
2,3,2020-01-06,12272.929018,12299.127043,12181.887534,12228.903255,3732.00,3835.84,-103.84,3778.78,...,360.0,1502.0,-0.17,0.0150,-0.21,-0.07,0.0877,-0.0690,-0.18,-0.170000
3,4,2020-01-07,12237.309351,12242.227141,12030.371144,12051.960005,3911.17,4593.40,-682.23,4205.16,...,1248.0,578.0,-0.21,-0.0500,-0.02,-1.79,-0.0437,-0.0208,0.08,-0.060000
4,5,2020-01-08,12149.137851,12192.474725,11985.555622,12017.343536,4109.04,4624.89,-515.85,5162.02,...,725.0,1109.0,0.56,0.3050,0.54,-0.59,-0.2980,-0.6992,-0.65,-0.340000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
353,354,2021-06-28,15829.576703,15869.452759,15764.937429,15838.276361,4275.71,5934.43,-1658.72,5634.19,...,1069.0,940.0,-0.90,-0.1242,-0.39,-0.96,0.1515,-0.3200,-0.19,0.140000
354,355,2021-06-29,15904.676773,15910.968841,15804.933350,15837.898386,10932.02,10815.39,116.63,8687.31,...,903.0,1084.0,-0.52,-0.3158,0.08,-0.26,0.0040,0.2000,-0.17,0.260000
355,356,2021-06-30,15858.319680,15870.707647,15770.343345,15787.255763,6057.48,7704.14,-1646.66,6171.14,...,965.0,1017.0,-0.02,-0.3200,0.30,-1.05,0.0520,-0.0300,0.15,-0.190001
356,357,2021-07-01,15811.641689,15852.728854,15739.926692,15742.949131,4395.80,5641.09,-1245.29,4721.48,...,NaN,NaN,0.18,0.0550,0.22,0.23,0.2160,0.2700,-0.10,-0.350000
357,358,2021-07-02,15773.078397,15783.784572,15693.999901,15692.806163,4860.51,5843.31,-982.80,4922.08,...,NaN,NaN,-0.65,0.1100,0.01,1.85,-0.0650,0.1600,0.21,-0.410000

In [4]:
df=pd.DataFrame(df)

In [5]:
df

,index,Date(IST),NFO,NFH,NFL,NFC,FIIB,FIIS,FIIN,DIIB,...,August,December,CAD,DAD,DOD,NDAD,Currey,Flow,Shine,Vega
0,1,2020-01-02,12115.673242,12177.119957,12151.571552,12216.272367,2670.78,1982.02,688.76,3490.16,...,1356.0,482.0,-0.01,0.3970,-0.98,0.72,-0.0520,0.0399,-0.10,-1.309999
1,2,2020-01-03,12195.406448,12275.487382,12173.355954,12251.196928,4514.35,3251.30,1263.05,2750.87,...,879.0,973.0,-0.23,-0.5100,-1.33,0.46,0.4430,0.5648,0.08,1.550000
2,3,2020-01-06,12272.929018,12299.127043,12181.887534,12228.903255,3732.00,3835.84,-103.84,3778.78,...,360.0,1502.0,-0.17,0.0150,-0.21,-0.07,0.0877,-0.0690,-0.18,-0.170000
3,4,2020-01-07,12237.309351,12242.227141,12030.371144,12051.960005,3911.17,4593.40,-682.23,4205.16,...,1248.0,578.0,-0.21,-0.0500,-0.02,-1.79,-0.0437,-0.0208,0.08,-0.060000
4,5,2020-01-08,12149.137851,12192.474725,11985.555622,12017.343536,4109.04,4624.89,-515.85,5162.02,...,725.0,1109.0,0.56,0.3050,0.54,-0.59,-0.2980,-0.6992,-0.65,-0.340000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
353,354,2021-06-28,15829.576703,15869.452759,15764.937429,15838.276361,4275.71,5934.43,-1658.72,5634.19,...,1069.0,940.0,-0.90,-0.1242,-0.39,-0.96,0.1515,-0.3200,-0.19,0.140000
354,355,2021-06-29,15904.676773,15910.968841,15804.933350,15837.898386,10932.02,10815.39,116.63,8687.31,...,903.0,1084.0,-0.52,-0.3158,0.08,-0.26,0.0040,0.2000,-0.17,0.260000
355,356,2021-06-30,15858.319680,15870.707647,15770.343345,15787.255763,6057.48,7704.14,-1646.66,6171.14,...,965.0,1017.0,-0.02,-0.3200,0.30,-1.05,0.0520,-0.0300,0.15,-0.190001
356,357,2021-07-01,15811.641689,15852.728854,15739.926692,15742.949131,4395.80,5641.09,-1245.29,4721.48,...,NaN,NaN,0.18,0.0550,0.22,0.23,0.2160,0.2700,-0.10,-0.350000
357,358,2021-07-02,15773.078397,15783.784572,15693.999901,15692.806163,4860.51,5843.31,-982.80,4922.08,...,NaN,NaN,-0.65,0.1100,0.01,1.85,-0.0650,0.1600,0.21,-0.410000

In [6]:
df.dtypes

index          int64
Date(IST)     object
NFO          float64
NFH          float64
NFL          float64
NFC          float64
FIIB         float64
FIIS         float64
FIIN         float64
DIIB         float64
DIIS         float64
DIIN         float64
August       float64
December     float64
CAD          float64
DAD          float64
DOD          float64
NDAD         float64
Currey       float64
Flow         float64
Shine        float64
Vega         float64
dtype: object

In [7]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
df['Date(IST)']=le.fit_transform(df['Date(IST)'])

In [8]:
df.isna().sum()

index        0
Date(IST)    0
NFO          0
NFH          0
NFL          0
NFC          0
FIIB         1
FIIS         1
FIIN         1
DIIB         1
DIIS         1
DIIN         1
August       2
December     2
CAD          0
DAD          0
DOD          0
NDAD         0
Currey       0
Flow         0
Shine        0
Vega         0
dtype: int64

In [9]:
pd.DataFrame.dropna(df,inplace=True)

In [10]:
df.isna().sum()

index        0
Date(IST)    0
NFO          0
NFH          0
NFL          0
NFC          0
FIIB         0
FIIS         0
FIIN         0
DIIB         0
DIIS         0
DIIN         0
August       0
December     0
CAD          0
DAD          0
DOD          0
NDAD         0
Currey       0
Flow         0
Shine        0
Vega         0
dtype: int64

In [11]:
df.describe()

,index,Date(IST),NFO,NFH,NFL,NFC,FIIB,FIIS,FIIN,DIIB,...,August,December,CAD,DAD,DOD,NDAD,Currey,Flow,Shine,Vega
count,355.000000,355.000000,355.000000,355.000000,355.000000,355.000000,355.000000,355.000000,355.000000,355.000000,...,355.000000,355.000000,355.000000,355.000000,355.000000,355.000000,355.000000,355.000000,355.000000,355.000000
mean,178.625352,177.625352,12392.743851,12472.301870,12280.436920,12379.724504,7683.328310,7412.260761,271.067465,4715.090310,...,979.898592,945.061972,0.006535,0.015977,0.024676,0.195915,0.008507,0.007079,0.004620,0.006451
std,103.030619,103.030619,2152.304776,2131.192420,2163.640851,2150.859412,5424.960365,4868.765079,2773.656749,1557.269879,...,592.413522,295.768713,1.153637,0.479575,1.429541,2.535846,0.277346,0.402349,0.659391,3.290018
min,1.000000,0.000000,7471.891708,7819.610704,7264.768634,7512.951040,2489.450000,1982.020000,-8295.170000,1960.270000,...,107.000000,312.000000,-4.770000,-2.510000,-8.440000,-10.740000,-1.485500,-3.078700,-2.470000,-17.639999
25%,89.500000,88.500000,10988.451423,11071.452300,10899.791747,10993.729871,5216.655000,5145.015000,-1004.570000,3694.195000,...,762.500000,742.500000,-0.575000,-0.205000,-0.805000,-1.035000,-0.141750,-0.178950,-0.340000,-1.225000
50%,179.000000,178.000000,12095.398276,12121.683483,11990.374901,12058.276607,6534.990000,6361.430000,146.220000,4342.900000,...,996.000000,889.000000,-0.020000,0.035000,0.010000,0.190000,0.004000,0.015000,0.000000,-0.210001
75%,267.500000,266.500000,14557.310080,14698.970930,14444.825602,14573.408730,8496.545000,8100.990000,1173.350000,5314.830000,...,1156.500000,1134.500000,0.525000,0.278350,0.940000,1.570000,0.142500,0.207450,0.315000,0.855000
max,356.000000,355.000000,15904.676773,15921.677431,15814.822034,15895.376149,74741.850000,67028.870000,28739.170000,13264.470000,...,10680.000000,1835.000000,4.470000,1.738000,4.600000,10.130000,1.211500,1.360000,3.140000,24.860001

In [12]:
df.corr()

,index,Date(IST),NFO,NFH,NFL,NFC,FIIB,FIIS,FIIN,DIIB,...,August,December,CAD,DAD,DOD,NDAD,Currey,Flow,Shine,Vega
index,1.000000,1.000000,0.829461,0.833498,0.827006,0.831356,0.201367,0.137368,0.152719,0.064173,...,0.061600,0.003651,0.072826,0.043401,0.059657,0.043517,-0.035024,0.141543,-0.058879,-0.034221
Date(IST),1.000000,1.000000,0.829461,0.833498,0.827006,0.831356,0.201367,0.137368,0.152719,0.064173,...,0.061600,0.003651,0.072826,0.043401,0.059657,0.043517,-0.035024,0.141543,-0.058879,-0.034221
NFO,0.829461,0.829461,1.000000,0.999278,0.999101,0.998676,0.161978,0.107903,0.127402,0.073352,...,0.003825,0.093393,0.045555,-0.044498,-0.026523,0.007938,-0.006341,0.069174,-0.085645,0.033644
NFH,0.833498,0.833498,0.999278,1.000000,0.998350,0.999249,0.165578,0.112310,0.126706,0.082719,...,0.003101,0.092777,0.042517,-0.045401,-0.027460,0.006707,-0.004392,0.067252,-0.082460,0.037597
NFL,0.827006,0.827006,0.999101,0.998350,1.000000,0.999189,0.157731,0.098022,0.136440,0.057374,...,0.007170,0.089401,0.046113,-0.043510,-0.027121,0.007721,-0.008389,0.069265,-0.087463,0.036056
NFC,0.831356,0.831356,0.998676,0.999249,0.999189,1.000000,0.161304,0.102740,0.135148,0.066701,...,0.006101,0.088816,0.041604,-0.046656,-0.030009,0.004461,-0.005946,0.066034,-0.084799,0.042139
FIIB,0.201367,0.201367,0.161978,0.165578,0.157731,0.161304,1.000000,0.860223,0.445887,0.212559,...,0.019301,-0.077105,-0.051588,0.019487,-0.038274,-0.029989,0.009060,0.082628,-0.077246,-0.013020
FIIS,0.137368,0.137368,0.107903,0.112310,0.098022,0.102740,0.860223,1.000000,-0.072860,0.389957,...,-0.060235,0.081124,-0.106959,-0.086752,-0.144078,-0.085343,0.099148,-0.018703,-0.087265,0.022812
FIIN,0.152719,0.152719,0.127402,0.126706,0.136440,0.135148,0.445887,-0.072860,1.000000,-0.268773,...,0.143484,-0.293211,0.086851,0.190396,0.178049,0.091153,-0.156319,0.194442,0.002097,-0.065509
DIIB,0.064173,0.064173,0.073352,0.082719,0.057374,0.066701,0.212559,0.389957,-0.268773,1.000000,...,-0.152399,0.263215,-0.099592,-0.160576,-0.106335,-0.160607,0.112556,-0.138491,-0.175206,0.054232
DIIS,0.353473,0.353473,0.340874,0.349675,0.339403,0.348861,0.446925,0.361695,0.239231,0.442487,...,-0.055966,0.110855,-0.065508,-0.045929,-0.010349,-0.064102,0.010276,0.040133,-0.139904,0.039627
DIIN,-0.233486,-0.233486,-0.213406,-0.211253,-0.228544,-0.226989,-0.160459,0.093608,-0.478156,0.650734,...,-0.108882,0.176036,-0.046654,-0.125765,-0.100272,-0.110409,0.106713,-0.175988,-0.061197,0.022056
August,0.061600,0.061600,0.003825,0.003101,0.007170,0.006101,0.019301,-0.060235,0.143484,-0.152399,...,1.000000,-0.494735,0.115998,0.221533,0.162943,0.121713,-0.251468,0.132388,0.015845,-0.094570
December,0.003651,0.003651,0.093393,0.092777,0.089401,0.088816,-0.077105,0.081124,-0.293211,0.263215,...,-0.494735,1.000000,-0.155616,-0.343955,-0.170023,-0.196640,0.257760,-0.236379,-0.090937,0.196268
CAD,0.072826,0.072826,0.045555,0.042517,0.046113,0.041604,-0.051588,-0.106959,0.086851,-0.099592,...,0.115998,-0.155616,1.000000,0.584655,0.626623,0.413672,-0.256550,0.362339,-0.042436,-0.458127
DAD,0.043401,0.043401,-0.044498,-0.045401,-0.043510,-0.046656,0.019487,-0.086752,0.190396,-0.160576,...,0.221533,-0.343955,0.584655,1.000000,0.657856,0.543111,-0.295619,0.427584,0.221848,-0.635528
DOD,0.059657,0.059657,-0.026523,-0.027460,-0.027121,-0.030009,-0.038274,-0.144078,0.178049,-0.106335,...,0.162943,-0.170023,0.626623,0.657856,1.000000,0.442709,-0.223694,0.504435,0.092340,-0.524468
NDAD,0.043517,0.043517,0.007938,0.006707,0.007721,0.004461,-0.029989,-0.085343,0.091153,-0.160607,...,0.121713,-0.196640,0.413672,0.543111,0.442709,1.000000,-0.255248,0.326085,0.283592,-0.549088
Currey,-0.035024,-0.035024,-0.006341,-0.004392,-0.008389,-0.005946,0.009060,0.099148,-0.156319,0.112556,...,-0.251468,0.257760,-0.256550,-0.295619,-0.223694,-0.255248,1.000000,-0.237907,-0.059926,0.184083
Flow,0.141543,0.141543,0.069174,0.067252,0.069265,0.066034,0.082628,-0.018703,0.194442,-0.138491,...,0.132388,-0.236379,0.362339,0.427584,0.504435,0.326085,-0.237907,1.000000,0.116577,-0.390567
Shine,-0.058879,-0.058879,-0.085645,-0.082460,-0.087463,-0.084799,-0.077246,-0.087265,0.002097,-0.175206,...,0.015845,-0.090937,-0.042436,0.221848,0.092340,0.283592,-0.059926,0.116577,1.000000,-0.187162
Vega,-0.034221,-0.034221,0.033644,0.037597,0.036056,0.042139,-0.013020,0.022812,-0.065509,0.054232,...,-0.094570,0.196268,-0.458127,-0.635528,-0.524468,-0.549088,0.184083,-0.390567,-0.187162,1.000000

In [13]:
from scipy.stats import zscore
z=np.abs(zscore(df))
z

array([[1.72643881, 1.72643881, 0.12891375, ..., 0.08168891, 0.15888503,
        0.40069936],
       [1.71671925, 1.71671925, 0.09181596, ..., 1.38811903, 0.11447936,
        0.46982355],
       [1.7069997 , 1.7069997 , 0.05574673, ..., 0.18935365, 0.28038032,
        0.05370786],
       ...,
       [1.70456297, 1.70456297, 1.59906894, ..., 0.81407066, 0.29556723,
        0.04064966],
       [1.71428252, 1.71428252, 1.63401105, ..., 0.48016378, 0.26519341,
        0.07717507],
       [1.72400207, 1.72400207, 1.6124423 , ..., 0.09228607, 0.22078773,
        0.05979557]])

In [14]:
threshold=3
print(np.where(z>3))

(array([ 37,  38,  38,  38,  43,  44,  44,  44,  44,  44,  44,  44,  46,
        46,  46,  46,  46,  46,  47,  47,  47,  48,  48,  48,  48,  49,
        49,  49,  50,  50,  51,  52,  53,  53,  54,  54,  54,  56,  60,
        61,  61,  62,  62,  64,  65,  65,  69,  80,  86,  94,  94,  96,
       103, 103, 103, 111, 144, 148, 153, 205, 206, 217, 217, 217, 217,
       254, 258, 273, 273, 275, 275, 275, 288, 289, 289, 295, 295, 299,
       331, 331, 345], dtype=int64), array([21,  9, 11, 18, 19,  9, 11, 14, 15, 16, 19, 21,  9, 13, 15, 16, 17,
       21,  9, 11, 21, 14, 15, 17, 21, 14, 16, 17,  9, 14, 14, 17, 17, 18,
       15, 17, 20, 18, 18, 19, 21, 15, 16, 20, 14, 16, 19,  8, 15,  6,  7,
       19, 15, 16, 21,  7, 20, 20, 12, 14, 10,  6,  7, 10, 11, 21, 10,  6,
        8,  7,  8, 18, 19,  6,  7,  9, 10, 18,  6,  7, 18], dtype=int64))

In [15]:
df=df[(z<3).all(axis=1)]
df

,index,Date(IST),NFO,NFH,NFL,NFC,FIIB,FIIS,FIIN,DIIB,...,August,December,CAD,DAD,DOD,NDAD,Currey,Flow,Shine,Vega
0,1,0,12115.673242,12177.119957,12151.571552,12216.272367,2670.78,1982.02,688.76,3490.16,...,1356.0,482.0,-0.01,0.3970,-0.98,0.72,-0.0520,0.0399,-0.10,-1.309999
1,2,1,12195.406448,12275.487382,12173.355954,12251.196928,4514.35,3251.30,1263.05,2750.87,...,879.0,973.0,-0.23,-0.5100,-1.33,0.46,0.4430,0.5648,0.08,1.550000
2,3,2,12272.929018,12299.127043,12181.887534,12228.903255,3732.00,3835.84,-103.84,3778.78,...,360.0,1502.0,-0.17,0.0150,-0.21,-0.07,0.0877,-0.0690,-0.18,-0.170000
3,4,3,12237.309351,12242.227141,12030.371144,12051.960005,3911.17,4593.40,-682.23,4205.16,...,1248.0,578.0,-0.21,-0.0500,-0.02,-1.79,-0.0437,-0.0208,0.08,-0.060000
4,5,4,12149.137851,12192.474725,11985.555622,12017.343536,4109.04,4624.89,-515.85,5162.02,...,725.0,1109.0,0.56,0.3050,0.54,-0.59,-0.2980,-0.6992,-0.65,-0.340000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
351,352,351,15832.780716,15871.734957,15673.598435,15711.203010,7094.36,9985.30,-2890.94,5377.76,...,783.0,1186.0,0.67,0.2234,-0.04,-0.16,0.0900,0.0880,0.01,-0.349999
352,353,352,15781.799179,15846.875708,15703.024907,15763.679655,6766.31,7445.15,-678.84,6844.01,...,1070.0,902.0,0.54,0.1000,0.18,0.27,-0.0515,0.1500,-0.08,-0.350000
353,354,353,15829.576703,15869.452759,15764.937429,15838.276361,4275.71,5934.43,-1658.72,5634.19,...,1069.0,940.0,-0.90,-0.1242,-0.39,-0.96,0.1515,-0.3200,-0.19,0.140000
354,355,354,15904.676773,15910.968841,15804.933350,15837.898386,10932.02,10815.39,116.63,8687.31,...,903.0,1084.0,-0.52,-0.3158,0.08,-0.26,0.0040,0.2000,-0.17,0.260000
355,356,355,15858.319680,15870.707647,15770.343345,15787.255763,6057.48,7704.14,-1646.66,6171.14,...,965.0,1017.0,-0.02,-0.3200,0.30,-1.05,0.0520,-0.0300,0.15,-0.190001

In [16]:
df.drop(['index'],axis=1,inplace=True)

In [17]:
df

,Date(IST),NFO,NFH,NFL,NFC,FIIB,FIIS,FIIN,DIIB,DIIS,...,August,December,CAD,DAD,DOD,NDAD,Currey,Flow,Shine,Vega
0,0,12115.673242,12177.119957,12151.571552,12216.272367,2670.78,1982.02,688.76,3490.16,3426.21,...,1356.0,482.0,-0.01,0.3970,-0.98,0.72,-0.0520,0.0399,-0.10,-1.309999
1,1,12195.406448,12275.487382,12173.355954,12251.196928,4514.35,3251.30,1263.05,2750.87,3780.07,...,879.0,973.0,-0.23,-0.5100,-1.33,0.46,0.4430,0.5648,0.08,1.550000
2,2,12272.929018,12299.127043,12181.887534,12228.903255,3732.00,3835.84,-103.84,3778.78,3802.48,...,360.0,1502.0,-0.17,0.0150,-0.21,-0.07,0.0877,-0.0690,-0.18,-0.170000
3,3,12237.309351,12242.227141,12030.371144,12051.960005,3911.17,4593.40,-682.23,4205.16,3893.97,...,1248.0,578.0,-0.21,-0.0500,-0.02,-1.79,-0.0437,-0.0208,0.08,-0.060000
4,4,12149.137851,12192.474725,11985.555622,12017.343536,4109.04,4624.89,-515.85,5162.02,4413.62,...,725.0,1109.0,0.56,0.3050,0.54,-0.59,-0.2980,-0.6992,-0.65,-0.340000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
351,351,15832.780716,15871.734957,15673.598435,15711.203010,7094.36,9985.30,-2890.94,5377.76,4239.00,...,783.0,1186.0,0.67,0.2234,-0.04,-0.16,0.0900,0.0880,0.01,-0.349999
352,352,15781.799179,15846.875708,15703.024907,15763.679655,6766.31,7445.15,-678.84,6844.01,5011.25,...,1070.0,902.0,0.54,0.1000,0.18,0.27,-0.0515,0.1500,-0.08,-0.350000
353,353,15829.576703,15869.452759,15764.937429,15838.276361,4275.71,5934.43,-1658.72,5634.19,4357.11,...,1069.0,940.0,-0.90,-0.1242,-0.39,-0.96,0.1515,-0.3200,-0.19,0.140000
354,354,15904.676773,15910.968841,15804.933350,15837.898386,10932.02,10815.39,116.63,8687.31,6877.26,...,903.0,1084.0,-0.52,-0.3158,0.08,-0.26,0.0040,0.2000,-0.17,0.260000
355,355,15858.319680,15870.707647,15770.343345,15787.255763,6057.48,7704.14,-1646.66,6171.14,4650.96,...,965.0,1017.0,-0.02,-0.3200,0.30,-1.05,0.0520,-0.0300,0.15,-0.190001

In [40]:
x=df.iloc[ : , [0,1,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20]]
x

,Date(IST),NFO,NFC,FIIB,FIIS,FIIN,DIIB,DIIS,DIIN,August,December,CAD,DAD,DOD,NDAD,Currey,Flow,Shine,Vega
0,0,12115.673242,12216.272367,2670.78,1982.02,688.76,3490.16,3426.21,63.95,1356.0,482.0,-0.01,0.3970,-0.98,0.72,-0.0520,0.0399,-0.10,-1.309999
1,1,12195.406448,12251.196928,4514.35,3251.30,1263.05,2750.87,3780.07,-1029.20,879.0,973.0,-0.23,-0.5100,-1.33,0.46,0.4430,0.5648,0.08,1.550000
2,2,12272.929018,12228.903255,3732.00,3835.84,-103.84,3778.78,3802.48,-23.70,360.0,1502.0,-0.17,0.0150,-0.21,-0.07,0.0877,-0.0690,-0.18,-0.170000
3,3,12237.309351,12051.960005,3911.17,4593.40,-682.23,4205.16,3893.97,311.19,1248.0,578.0,-0.21,-0.0500,-0.02,-1.79,-0.0437,-0.0208,0.08,-0.060000
4,4,12149.137851,12017.343536,4109.04,4624.89,-515.85,5162.02,4413.62,748.40,725.0,1109.0,0.56,0.3050,0.54,-0.59,-0.2980,-0.6992,-0.65,-0.340000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
351,351,15832.780716,15711.203010,7094.36,9985.30,-2890.94,5377.76,4239.00,1138.76,783.0,1186.0,0.67,0.2234,-0.04,-0.16,0.0900,0.0880,0.01,-0.349999
352,352,15781.799179,15763.679655,6766.31,7445.15,-678.84,6844.01,5011.25,1832.76,1070.0,902.0,0.54,0.1000,0.18,0.27,-0.0515,0.1500,-0.08,-0.350000
353,353,15829.576703,15838.276361,4275.71,5934.43,-1658.72,5634.19,4357.11,1277.08,1069.0,940.0,-0.90,-0.1242,-0.39,-0.96,0.1515,-0.3200,-0.19,0.140000
354,354,15904.676773,15837.898386,10932.02,10815.39,116.63,8687.31,6877.26,1810.05,903.0,1084.0,-0.52,-0.3158,0.08,-0.26,0.0040,0.2000,-0.17,0.260000
355,355,15858.319680,15787.255763,6057.48,7704.14,-1646.66,6171.14,4650.96,1520.18,965.0,1017.0,-0.02,-0.3200,0.30,-1.05,0.0520,-0.0300,0.15,-0.190001

In [46]:
y=df.iloc[ : ,2:4]
y

              NFH           NFL
0    12177.119957  12151.571552
1    12275.487382  12173.355954
2    12299.127043  12181.887534
3    12242.227141  12030.371144
4    12192.474725  11985.555622
..            ...           ...
351  15871.734957  15673.598435
352  15846.875708  15703.024907
353  15869.452759  15764.937429
354  15910.968841  15804.933350
355  15870.707647  15770.343345

[313 rows x 2 columns]

In [45]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=.30,random_state=43)

In [47]:
import numpy as np
import pandas as pd
import sklearn
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error,mean_absolute_error,r2_score
from sklearn.model_selection import train_test_split
import warnings
warnings.filterwarnings('ignore')

from sklearn.multioutput import MultiOutputRegressor
from sklearn.linear_model import Ridge

In [72]:
from sklearn.linear_model import Lasso,Ridge

In [75]:
rd=Ridge(alpha=0.01)              
rd.fit(x_train,y_train)
rdpred=rd.predict(x_test)
print('score: ',rd.score(x_train,y_train))
print('Mean absolute error: ',mean_absolute_error(y_test,rdpred))
print('Mean squared error:  ',mean_squared_error(y_test,rdpred))
print('Root mean squared error: ',np.sqrt(mean_squared_error(y_test,rdpred)))
print('r2_score: ',r2_score(y_test,rdpred))

score:  0.9996077560739745
Mean absolute error:  29.073691568646844
Mean squared error:   1429.999346670589
Root mean squared error:  37.81533216395949
r2_score:  0.9996559199012117

In [76]:
ls=Lasso(alpha=0.01)
ls.fit(x_train,y_train)
lspred=ls.predict(x_test)
print('score: ',ls.score(x_train,y_train))
print('Mean absolute error: ',mean_absolute_error(y_test,lspred))
print('Mean squared error:  ',mean_squared_error(y_test,lspred))
print('Root mean squared error: ',np.sqrt(mean_squared_error(y_test,lspred)))
print('r2_score: ',r2_score(y_test,lspred))

score:  0.9995905824152665
Mean absolute error:  28.846283183152536
Mean squared error:   1469.16406597314
Root mean squared error:  38.32967604837197
r2_score:  0.9996465305002126

In [77]:
from sklearn.linear_model import ElasticNet
enr=ElasticNet(alpha=0.01)
enr.fit(x_train,y_train)
enrpred=enr.predict(x_test)
print('score: ',enr.score(x_train,y_train))
print('Mean absolute error: ',mean_absolute_error(y_test,enrpred))
print('Mean squared error:  ',mean_squared_error(y_test,enrpred))
print('Root mean squared error: ',np.sqrt(mean_squared_error(y_test,enrpred)))
print('r2_score: ',r2_score(y_test,enrpred))

score:  0.9995905085252356
Mean absolute error:  28.77129676534006
Mean squared error:   1459.7799858571516
Root mean squared error:  38.20706722397247
r2_score:  0.9996487901516864

In [81]:
from sklearn.model_selection import cross_val_score,cross_val_predict
rdcv=Ridge(alpha=0.01)
rdcvs=cross_val_score(rdcv,x,y,cv=8)
print('mean score: ',rdcvs.mean())
predrdcv=cross_val_predict(rdcv,x,y,cv=8)

mean score:  0.9808234806412317

In [86]:
from sklearn.ensemble import RandomForestRegressor
rfr=RandomForestRegressor()
rfr.fit(x_train,y_train)
print('score: ',rfr.score(x_train,y_train))
predrfr=rfr.predict(x_test)
print('Mean absolute error: ',mean_absolute_error(y_test,predrfr))
print('Mean squared error:  ',mean_squared_error(y_test,predrfr))
print('Root mean squared error: ',np.sqrt(mean_squared_error(y_test,predrfr)))
print('r2_score: ',r2_score(y_test,predrfr))

score:  0.9997025420438794
Mean absolute error:  54.08259564262451
Mean squared error:   5358.239858650115
Root mean squared error:  73.19999903449532
r2_score:  0.9987107386054697

In [ ]:
# Therefore We are getting maximum score and max r2_score through Ridge algorithm. We have to save the model of ridge.